User Preference Microservice in Java
====================================

This is an example showing a complete solution that how DynamoDB works in Java 8.

Highlights like Hash Key, Range Key, DynamoDBMapper, Pagination solution in DynamoDB, and using Mock Server to mock DynamoDB table and item operations.

Hot Reload Java classes without restarting the container
--------------------------------------------------------

Configure IntelliJ IDEA then start running command in one terminal window at first:

[source.console]
----
𝜆 eval $GRADLE_HOME/bin/gradle -t classes
Continuous build is an incubating feature.
The plus(Iterable<FileCollection>) method and using the '+' operator in conjunction with an Iterable<FileCollection> object have been deprecated and are scheduled to be removed in 3.0.  Please use the plus(FileCollection) method or the '+' operator with a FileCollection object instead.
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE

BUILD SUCCESSFUL

Total time: 5.533 secs

Waiting for changes to input files of tasks... (ctrl-d to exit)
modified: /Users/terrence/Projects/AWS/dynamodb-java/src/main/java/org/paradise/microservice/userpreference/controller/UserPreferenceController.java
Change detected, executing build...

:compileJava
:processResources UP-TO-DATE
:classes

BUILD SUCCESSFUL

Total time: 5.918 secs

Waiting for changes to input files of tasks... (ctrl-d to exit)
----

Run application in another terminal window secondly:

[source.console]
----
𝜆 env SPRING_PROFILES_ACTIVE=local $GRADLE_HOME/bin/gradle bootRun
The plus(Iterable<FileCollection>) method and using the '+' operator in conjunction with an Iterable<FileCollection> object have been deprecated and are scheduled to be removed in 3.0.  Please use the plus(FileCollection) method or the '+' operator with a FileCollection object instead.
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:findMainClass
:bootRun
objc[34888]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java (0x1065334c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1085bb4e0). One of the two will be used. Which one is undefined.

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.2.RELEASE)

----

AWS SQS
-------

Need to have access AWS SQS to start running this application. Create an application.properties file, under src/main/resources directory, with:

[source.console]
----
cloud.aws:
  credentials.accessKey: AWS Access Key
  credentials.secretKey: AWS Secret Key
----

then run application and all functional test, attributes in application.properties file ALL can inject in.

DynamoDB Local
--------------

Download DynamoDB Local (actually it's a DynamoDB Mock based on SQLite database with added-on DynamoDB API.

Start DynamoDB Local:

[source.console]
----
𝜆 java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal-DEBUG.jar -sharedDb -port 9000

Initializing DynamoDB Local with the following configuration:
Port:	9000
InMemory:	false
DbPath:	null
SharedDb:	true
shouldDelayTransientStatuses:	false
CorsParams:	*
----

Redis server
------------

Redis Server need to be running when run Health Check functional test. Run Redis Server and CLI by using Docker image:

[source.console]
----
𝜆 docker run --name session -d redis

𝜆 docker run -it --link session:redis --rm redis redis-cli -h redis -p 6379
----

References
----------
- Query, Scan and Pagination Operations in DynamoDB, _http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/QueryAndScan.html_
- Limits in DynamoDB, _http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html_
- Local Secondary Indexes in DynamoDB, _http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/LSI.html_
- Global Secondary Indexes in DynamoDB, _http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html_
- Spring RequestMapping, _http://www.baeldung.com/spring-requestmapping_
- Spring Cloud AWS, _http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html_
- Extracting a JSON Response with Rest-Assured, _http://james-willett.com/2015/06/extracting-a-json-response-with-rest-assured/_
- Spring Batch ItemReaders and ItemWriters, _http://docs.spring.io/spring-batch/reference/html/readersAndWriters.html_
- Spring Batch Tutorial: Writing Information to a File, _https://www.petrikainulainen.net/programming/spring-framework/spring-batch-tutorial-writing-information-to-a-file/_
- Spring Batch- Read From MySQL database & write to CSV file, _http://websystique.com/springbatch/spring-batch-read-from-mysql-database-and-write-to-a-csv-file/_
- Spring Hot swapping, _http://docs.spring.io/spring-boot/docs/current/reference/html/howto-hotswapping.html_
- Gradle: Introducing Continuous Build Execution, _https://blog.gradle.org/introducing-continuous-build_
- Spring Sweets: Reload Classes Spring Boot With Spring Loaded And Gradle Continuous Build, _http://mrhaki.blogspot.com.au/2015/09/spring-sweets-reload-classes-spring.html_
- Implementing feature toggles for a Spring Boot application, _https://sdqali.in/series/feature-toggles/_
- Integration Testing a Spring Boot Application, _https://blog.jayway.com/2014/07/04/integration-testing-a-spring-boot-application/_
- Customize the Jackson ObjectMapper in Spring Boot / Spring MVC globally, _http://docs.spring.io/spring-boot/docs/current/reference/html/howto-spring-mvc.html#howto-customize-the-jackson-objectmapper_
- Unit Test Spring MVC Rest Service: MockMVC, JUnit, Mockito, _http://memorynotfound.com/unit-test-spring-mvc-rest-service-junit-mockito_
- Spring Boot Actuator: Production-ready features, _https://github.com/spring-projects/spring-boot/blob/master/spring-boot-docs/src/main/asciidoc/production-ready-features.adoc_
- Common Spring Boot properties, _http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html_
- Ajax and JWT Authentication Tutorial: An example using Spring Boot, _http://www.svlada.com/jwt-token-authentication-with-spring-boot/_