Resources:
  DBShutDownFunctionServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  DBShutDownFunctionServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: rds:StopDBInstance
            Effect: Allow
            Resource:
              - arn:aws:rds:ap-southeast-2:004385754915:db:db-startup-shutdown-lambda-mysql
              - arn:aws:rds:ap-southeast-2:004385754915:db:db-startup-shutdown-lambda-postgresql
        Version: "2012-10-17"
      PolicyName: DBShutDownFunctionServiceRoleDefaultPolicy
      Roles:
        - Ref: DBShutDownFunctionServiceRole
  DBShutDownFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: DBShutDownFunctionLambdaSourceBucketNameParameter
        S3Key:
          Ref: DBShutDownFunctionLambdaSourceObjectKeyParameter
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - DBShutDownFunctionServiceRole
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          MYSQL_INSTANCE_IDENTIFIER: db-startup-shutdown-lambda-mysql
          POSTGRESQL_INSTANCE_IDENTIFIER: db-startup-shutdown-lambda-postgresql
      MemorySize: 128
      Timeout: 300
    DependsOn:
      - DBShutDownFunctionServiceRoleDefaultPolicy
      - DBShutDownFunctionServiceRole
  DBShutDownFunctionAllowEventRuleLambdaStackDBShutDownRule:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DBShutDownFunction
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - DBShutDownRule
          - Arn
  DBShutDownRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 20 ? * MON-FRI *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - DBShutDownFunction
              - Arn
          Id: Target0
  DBStartUpFunctionServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  DBStartUpFunctionServiceRoleDefaultPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action: rds:StartDBInstance
            Effect: Allow
            Resource:
              - arn:aws:rds:ap-southeast-2:004385754915:db:db-startup-shutdown-lambda-mysql
              - arn:aws:rds:ap-southeast-2:004385754915:db:db-startup-shutdown-lambda-postgresql
        Version: "2012-10-17"
      PolicyName: DBStartUpFunctionServiceRoleDefaultPolicy
      Roles:
        - Ref: DBStartUpFunctionServiceRole
    Metadata:
      aws:cdk:path: LambdaStack/DBStartUpFunction/ServiceRole/DefaultPolicy/Resource
  DBStartUpFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: DBStartUpFunctionLambdaSourceBucketNameParameter
        S3Key:
          Ref: DBStartUpFunctionLambdaSourceObjectKeyParameter
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
          - DBStartUpFunctionServiceRole
          - Arn
      Runtime: nodejs12.x
      Environment:
        Variables:
          MYSQL_INSTANCE_IDENTIFIER: db-startup-shutdown-lambda-mysql
          POSTGRESQL_INSTANCE_IDENTIFIER: db-startup-shutdown-lambda-postgresql
      MemorySize: 128
      Timeout: 300
    DependsOn:
      - DBStartUpFunctionServiceRoleDefaultPolicy
      - DBStartUpFunctionServiceRole
  DBStartUpFunctionAllowEventRuleLambdaStackDBStartUpRule:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - DBStartUpFunction
          - Arn
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - DBStartUpRule
          - Arn
  DBStartUpRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 8 ? * MON-FRI *)
      State: ENABLED
      Targets:
        - Arn:
            Fn::GetAtt:
              - DBStartUpFunction
              - Arn
          Id: Target0
Parameters:
  DBShutDownFunctionLambdaSourceBucketNameParameter:
    Type: String
    Default: db-startup-shutdown-lambda-bucket
  DBShutDownFunctionLambdaSourceObjectKeyParameter:
    Type: String
    Default: shutdown.zip
  DBStartUpFunctionLambdaSourceBucketNameParameter:
    Type: String
    Default: db-startup-shutdown-lambda-bucket
  DBStartUpFunctionLambdaSourceObjectKeyParameter:
    Type: String
    Default: startup.zip

