
Load data into MySQL by using LOAD DATA INFILE for fixed width data files
-------------------------------------------------------------------------

Login MySQL database, and run the following command to load the CSV data (without CSV Headers) into database table.

[source.console]
----
sql> LOAD DATA INFILE '/Users/terrence/Projects/AWS/rhino/data/Article Event Metadata.csv' INTO TABLE event_metadata FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' (APP, FIELD_DESCRIPTION, FIELD_NAME, FIELD_TYPE, OBJECT_NAME);

sql> LOAD DATA INFILE '/Users/terrence/Projects/AWS/rhino/data/Article Event Data.csv' INTO TABLE event FIELDS TERMINATED BY ',' LINES TERMINATED BY '\r\n' (ID, REQUEST, DATAPAKID,RECORD, BIC_EVM_GUID, EH_GUID, BIC_ARTICLE, BIC_WORKCTR, BIC_DEVUSRID, BIC_EXTEVENT, BIC_MANIFEST, BIC_MERLOCID, BIC_PRODUCT, BIC_SUBPROD,RECORDMODE, BIC_DATETIMEL, BIC_SERVICE, BIC_DEVICESRC, BIC_SENDERID, BIC_WCCTYPE, BIC_DRV1STACC, BIC_DRV1STDEL, BIC_DEL1STDT, BIC_ACC1STDT, BIC_ODPEVTFLG, BIC_CON1STACC, BIC_CON1STDEL, BIC_WC1STACC, BIC_WC1STDEL, BIC_ACQUITFAC, BIC_CONTRACT, BIC_SIGNATURE, BIC_COMMS, BIC_CONSIGN, BIC_ROUNDNO, BIC_DEVICEID, EVENT_CD, BIC_PARCELCNT, BIC_BULKDMID, BIC_SCANCAT1, BIC_SCANCAT2, BIC_SCANCAT3, BIC_SCANQTY1, BIC_SCANQTY2, BIC_SCANQTY3, BIC_CONSJID, BIC_LOD_DATE, BIC_WCLODGE, BIC_DUE_DATE, BIC_IN_DUE_DT, BIC_CUSTREC, BIC_SUBURBREC, BIC_PCODEREC, BIC_STOP_CK, BIC_STOP_TIME, BIC_STOP_DATE, BIC_STOP_SRC, BIC_PCODEFROM, BIC_INTT_STA, BIC_EXTT_STA, BIC_DELEVENT, BIC_HELDEVENT, BIC_DELDATE, BIC_PCODETO, BIC_COMMREAS, BIC_DRVTMSLOT, BIC_EVNTDTLOC, BIC_EVNTTMLOC, BIC_MSGDTLOC, BIC_MSGTMLOC, BIC_EVNTDTUTC, BIC_EVNTTMUTC, BIC_MSGDTUTC, BIC_MSGTMUTC, BIC_RT_COL_DT, BIC_APRTDELEV, BIC_LATETRANS, BIC_DISDATTM, BIC_DISDTMSG, BIC_TIMETABLE, BIC_DLVRNTWRK, BIC_FACNART, BIC_SCCSPDEL, BIC_SCCDPDEL, BIC_SCUPLDEL, BIC_TASEVENT, BIC_TAUEVENT, BIC_CRDEVENT, BIC_UNDEVENT, BIC_DAMEVENT, BIC_MISEVENT, BIC_RTSEVENT, BIC_TPEVENT, BIC_MFSTLEVNT, BIC_MFSTAEVNT, BIC_LODEVENT, BIC_ACEVENT, BIC_PSEVENT, BIC_MFSTLODDT, BIC_MFSTLODTM, BIC_MFSTACMDT, BIC_MFSTACMTM, BIC_SCDELDATE, BIC_SCDELDAY1, BIC_SCDELDAY2, BIC_SCDELDAY3, BIC_SCDELDAY4, BIC_SCDELDAY5, BIC_SCDELDAY6, BIC_SCDELDAY7, BIC_SCEMBARGO, BIC_SCNDLDY1, BIC_SCNDLDY2, BIC_SCNDLDY3, BIC_SCNDLDY4, BIC_SCNDLDY5, BIC_SCNDLDY6, BIC_SCNDLDY7, BIC_SCDELTM1, BIC_SCDELTM2, BIC_SCDELTM3, BIC_SCDELTM4, BIC_SCDELTM5, BIC_SCDELTM6, BIC_SCDELTM7, BIC_SCREDIR, BIC_SCSURVEY, BIC_EXPDELDT, BIC_PROCDATE, BIC_EHMSEQNBR, BIC_MSGRECDTE, BIC_MSGRECTME, BIC_EVENTDATE, BIC_EVENTTIME, BIC_ORIGLOC, BIC_DESTLOC, BIC_LODTMSTMP, BIC_FACACCEV, BIC_FACACDT, BIC_WCFACAC, BIC_USERROLE, BIC_WCCROUND, BIC_BPARTNER, BIC_UNSUITRSN, BIC_CALLHDATE, BIC_CALLHTIME, BIC_CALLHEVNT, BIC_FACACTM, BIC_TTPNAME, BIC_TTPTIME, BIC_TTPDATE, BIC_CALHREASN, BIC_ATPDELEVT, BIC_ATPDELDT, BIC_TTPWRKCTR, BIC_CALWRKCTR, BIC_RSNCODET1, BIC_RSNCODET2, BIC_XLSERCODE, BIC_ARTICORG, BIC_FREETXT1, BIC_FREETXT2, BIC_RTAUTCODE, BIC_ARTCONDES, BIC_SNDRSUB, BIC_SNDRPCODE, BIC_SNDRNAME2, BIC_SNDRCOMP, BIC_SNDRSTATE, BIC_SNDRCNTRY, BIC_RECCOMP, BIC_DECLENGTH, BIC_DECHEIGHT, BIC_DECWIDTH, BIC_DECWEIGHT, BIC_DEC_UNIT, BIC_RETNCOST, BIC_CURRENCY, BIC_DECLENUOM, BIC_DECHGTUOM, BIC_DECWDTUOM, BIC_PLSIZE, BIC_ARTDELEV, BIC_ARTONBEV, BIC_ARTPRCEV, BIC_ARTACCEV, BIC_ARTCRTDT, BIC_ARTCRTTM, BIC_RTNSOURCE, BIC_ACTWEIGHT, BIC_ACTHEIGHT, BIC_ACTLENGTH, BIC_ACTWIDTH, BIC_ACT_UNIT, BIC_ACTHGTUOM, BIC_ACTLENUOM, BIC_ACTWDTUOM, BIC_SERVCODE, BIC_EXPDATTIM, BIC_SCRESH, BIC_MPAID,PARTNO, BIC_LFTD_IND, BIC_LFTW_IND, BIC_COURIER, BIC_RECSTATE, BIC_RECCNTRY, BIC_ADDRLINE1, BIC_ADDRLINE2, BIC_ADDRLINE3, BIC_ADDRLINE4, BIC_PCPROCESS, BIC_PCREASNID, BIC_PCREASNTX, BIC_SIGAUTHTY, BIC_RECDPID, BIC_MOBILE, BIC_EMAILADDR, BIC_COUREXTID, BIC_COUREXTTX, BIC_AGGSTAT, BIC_TRACKTPAD, BIC_TRACKIDAD, BIC_TRACKTPRM, BIC_TRACKIDRM, BIC_DEAGGLVL, BIC_CARRIER, BIC_DESTAGG, BIC_DEPDATTIM);
----
